### ISSUE TITLE
Binaries/installer packages

### ISSUE THREAD

**Issue by jumpinjackie** [vovkos/doxyrest#1]
Do you have any plans for binary/installer packages (especially on Windows)?

**Comment by vovkos** [comment]
Absolutely. Not sure about msi/deb/rpm installers, but portable archives with binaries (built and packages on Travis CI and AppVeyor) will be uploaded as GitHub release artifacts. As of now, there are no tagged releases yet, but there will be in the near future.

**Comment by vovkos** [comment]
I have finally updated Travis/AppVeyor scripts to publish GitHub releases on tagged commits. As of now, the only release v1.1.0 contains packages for Ubuntu 32-bit/64-bit, Windows 32-bit/64-bit and Mac OS X.
