### ISSUE TITLE
Static const field: Can we add the values as well?

### ISSUE THREAD

**Issue by strasdat** [vovkos/doxyrest#17]
I very much like the documentation doxyrest creates by default. But it would be great if static const "fields" could also show the value. I do not want to force the values into the comments, since this is pretty redundant and prone to refactoring errors.

![image](https://user-images.githubusercontent.com/584721/58653105-ded43f80-82c9-11e9-87ea-6b59e1a2c889.png)

E.g. I would expect to see:
``static int constexpr DoF = 3;``

http://strasdat.github.io/Sophus/class_Sophus_SO3Base.html#doxid-class-sophus-1-1-s-o3-base

**Comment by vovkos** [comment]
Good point, initializers should be displayed for variables/constants. Fixed.

Also, I can see you already use Doxyrest for documentation of your project -- nice! I noticed a glitch in the formatting of default parameters for template values (e.g. ``SO3Base::operator*=``); added a quick fix which should take care of it, too.

**Comment by strasdat** [comment]
Awesome, thanks!
