### ISSUE TITLE
using instead of typedef

### ISSUE THREAD

**Issue by strasdat** [vovkos/doxyrest#18]
This is just a minor comment. But I'm a big fan of modern c++; so I'd suggest to display

```
using Foo = FooType;
```

instead of

```
typeded FooType Foo;
```
, at least optionally.

**Comment by vovkos** [comment]
Added a new setting ``TYPEDEF_TO_USING``. When it's ``true``, the C++11-style ``using`` aliases are employed; classic ``typedef``-s are used otherwise.
