### ISSUE TITLE
Readme diagram?

### ISSUE THREAD

**Issue by minouye** [vovkos/doxyrest#2]
Apologies for using issues for this, but could you share how you created the diagram in your readme? I'd love to create something similar for my own project.

**Comment by vovkos** [comment]
I'm afraid my answer will not help much :) I asked our company' designer to do the diagram. I think he used Illustrator for the job, but I can double check on Monday.

**Comment by minouye** [comment]
@vovkos Ah that would explain why it looks so great :) Thanks for the reply!
