### ISSUE TITLE
conda recipe

### ISSUE THREAD

**Issue by raphaeldussin** [vovkos/doxyrest#22]
Hi @vovkos 

your tool looks very interesting. Have you considered making a conda recipe to make it easier to install within a readthedocs project?

**Comment by vovkos** [comment]
TBH I never used conda-build or hosted docs on readthedocs. However, I understand the importance of convenient integration with the whole readthedocs infrastructure. 

Could you please outline what has to be done here?

**Comment by raphaeldussin** [comment]
I have done it only for python packages but I'm sure we can figure out how to do it. I would start with this: https://conda-forge.org/
my guess is that we need to include a build script that reproduces the install instructions of doxyrest_b

https://docs.conda.io/projects/conda-build/en/latest/concepts/recipe.html

**Comment by vovkos** [comment]
A doxyrest recipe PR to conda-forge passed all the CI tests; pending approval.

https://github.com/conda-forge/staged-recipes/pull/9190

**Comment by raphaeldussin** [comment]
that's excellent news! looking forward to it!

**Comment by vovkos** [comment]
Wow, that was fast! The PR is merged and added to ``conda-forge/feedstocks``:

https://github.com/conda-forge/doxyrest-feedstock

It means, Doxyrest can now be installed from the ``conda-forge`` channel on Linux and OSX.
