### ISSUE TITLE
WARNING: the doxyrest extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit

### ISSUE THREAD

**Issue by andreyizrailev** [vovkos/doxyrest#28]
Hello,
Could you please fix it?
I think you might want to check this: https://www.sphinx-doc.org/en/stable/extdev/index.html#extension-metadata

**Comment by vovkos** [comment]
Good point.

[This commit](https://github.com/vovkos/doxyrest/commit/66cdaa3f175430697cd3e7371a8700eee6de4263) adds metadata for Doxyrest extensions marking them safe for parallel-read/write -- which should take care of the warning.

Double-check if it works for you, and if it does, please close the issue.

**Comment by andreyizrailev** [comment]
It works fine, thanks! When do you plan to make a new release?
