### ISSUE TITLE
Keep group order

### ISSUE THREAD

**Issue by andreyizrailev** [vovkos/doxyrest#29]
Hello!
Is there a way to keep a group order as it is in xml? `SORT_GROUPS_BY` supports only to values: sorting by title and by name. But what if I do not want them to be reordered anyhow? I've tried to remove `table.sort(compound.groupArray, cmpGroups)` in different files in lua frames, but the groups were still reordered.

**Comment by vovkos** [comment]
Could you please attach a zipped XML database to demonstrate the issue?  
![Uploading IMG_0002.jpg…]()

**Comment by vovkos** [comment]
Accidentally pressed "Close and comment" before finishing the previous message.

**Comment by andreyizrailev** [comment]
[my_xml.tar.gz](https://github.com/vovkos/doxyrest/files/4365644/my_xml.tar.gz)
Here it is. The problem occurs with `group__big__group` (sorry for namings): I want `group__page__b` go before `group__page__a`, but in generated `group_big_group.rst` in `toctree` directive the order is changed.

**Comment by vovkos** [comment]
[This commit](https://github.com/vovkos/doxyrest/commit/71244b66736556490d22db826bc5259ea8db60fc) adds a field called ``originalIdx`` to group compounds; it can be used to sort groups back to the original order as seen in the XML database. Please try it (pull master and rebuild) and let me know.

However, I would recommend against using this approach in a large project (where controlling the order in XML is nearly impossible). The preferred way of ordering groups should be ``grouporder``, see here:

https://vovkos.github.io/doxyrest/manual/group-order.html

**Comment by ol-andreyizrailev** [comment]
It works for me, thanks a lot!

**Comment by andreyizrailev** [comment]
It works for me, thanks a lot!
