### ISSUE TITLE
undefined label in ref-code-block 

### ISSUE THREAD

**Issue by Spenser309** [vovkos/doxyrest#33]
Hi,

Doxyrest seems to be somewhat working in my environment.  However, none of the links in the code are working.  I'm getting the following warning messages. 

> `/tmp/build/docs/sphinx/rst-dir/class_mla_AddElementWise.rst::` WARNING: undefined label:  (if the link has no caption the label must precede a section header)`

This is coming from a block like the following

> .. ref-code-block:: cpp
>      :class: doxyrest-overview-code-block
>
>      #include <add_element_wise.h>
>
>      class AddElementWise: public :ref:`mla::BinaryElementWise<doxid-classmla_1_1BinaryElementWise>`

If I manually insert a ref into the page outside of the ref-code-block (and remove the ref code block) the error is not generated and the link is created correctly.

> :ref:`<doxid-classmla_1_1BinaryElementWise>`

Any ideas on what may be causing this? 

FWIW: This is sphinx 3.2.0

**Comment by vovkos** [comment]
Could you please attach a sample project?

**Comment by Spenser309** [comment]
@vovkos no problem what files do you need?

**Comment by vovkos** [comment]
I need the header/source files which generate those faulty links -- basically, I need to reproduce the issue on my machine.

**Comment by Spenser309** [comment]
@vovkos I created a sample project here.  https://github.com/Spenser309/hello_doxyrest .

```
$ git clone git@github.com:Spenser309/hello_doxyrest.git
$ sudo mv $DOXYREST_DIR/lib/cmake/{doxyrest_config.cmake,doxyrest-config.cmake}
$ cd hello_doxyrest
$ mkdir build
$ cd build
$ cmake ..
$ make 
$ ./hello/hello
HELLO
WORLD
$ make sphinx-docs
...
Running plantuml with JAVA...
Running dot...
lookup cache used 17/65536 hits=70 misses=20
finished...
[ 50%] Built target doxygen
[100%] Sphinx Docs
Running Sphinx v3.0.4
loading translations [en]... done
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 5 source files that are out of date
updating environment: 0 added, 5 changed, 0 removed
reading sources... [100%] cpp-api/namespace_hello
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
/mnt/project/hello_doxyrest/build/docs/sphinx/cpp-api/class_hello_world.rst:: WARNING: undefined label: doxid-classBar (if the link has no caption the label must precede a section header)
/mnt/project/hello_doxyrest/build/docs/sphinx/cpp-api/global.rst:: WARNING: undefined label: doxid-classBar (if the link has no caption the label must precede a section header)
generating indices...  genindexdone
writing additional pages...  searchdone
copying static files... ... done
...
```

**Comment by Spenser309** [comment]
Added Dockerfile and instructions

**Comment by Spenser309** [comment]
@vovkos is that enough information to reproduce the issue on your side?

**Comment by vovkos** [comment]
Apologies for the late reply. Yes, that was enough to reproduce the issue. Thank you for providing a sample ready-to-run project -- I wish all bug reports were like this :)

The problem in this case is that Sphinx doesn't support mixed-case labels, but it reports it in a non-obvious way (by not being able to find a label). By default, Doxygen generates mixed-case labels (mangling the original identifiers of a C/C++ program). Luckily, it can be forced to generate lower-case labels with:
```
CASE_SENSE_NAMES=NO
```
If you add
```
set(DOXYGEN_CASE_SENSE_NAMES NO)
```
somewhere to your root ``CMakeLists.txt`` then the issue disappears.

Let me know if it works for you.

**Comment by Spenser309** [comment]
Hi @vovkos ,  Thank you for your response!  and for liking my bug report :) I'm glad you were able to reproduce the issue.  The solution you provided works perfectly for me!
