### ISSUE TITLE
Make it possible to reference using :any: role

### ISSUE THREAD

**Issue by johanseland** [vovkos/doxyrest#37]
Would it be possible to ensure that the cref domain is loaded into the list of domains that is searched when using the RST :any: role?

Currently I must either use :cref:`Foo::Bar` or `Foo::Bar` if I enable the default role.
However, I would like to be able to resolve Doxyrest generated references using e.g. :any:`Foo::Bar`

**Comment by vovkos** [comment]
Good point. The solution is to register a domain in the Sphinx extension. Then we can process the ``cref`` database when Sphinx is handling ``:any:`` links (essentially, it enumerates all registered domains and calls ``Domain.resolve_any_xref``).

Please check the [latest commit](https://github.com/vovkos/doxyrest/commit/b6a93c5a4f802ef53cb2418421413160b0b58a5e) and let me know if it works for you.

**Comment by johanseland** [comment]
Thanks - I will try it out and give you feedback.

**Comment by johanseland** [comment]
I am happy to report that you patch works exactly as I wanted. Thank you so much and merry Christmas!

**Comment by vovkos** [comment]
I personally try to avoid markdown as much as possible, only use reStructruredText -- even for GitHub READMEs ;) And inside RST I also prefer not to use the ``:any:`` role. But I know that the official Sphinx documentation recommends setting ``:any:`` as the default role, so your proposal totally made sense (and wasn't hard to implement).

Closing this issue.

Merry Christmas and Happy New Year to you too!
