### ISSUE TITLE
error while loading shared libraries: libexpat.so.1

### ISSUE THREAD

**Issue by ArchieMittal** [vovkos/doxyrest#43]
I am trying to configure doxyrest for my project where I want to convert doxygen documentation into rst format, but getting issues while running it. It is not able to load libexpat.so.1, although I see it is present in many locations.

Command to run doxyrest: 
`$ doxyrest-2.1.2-linux-x86/bin/doxyrest -c doxyrest-config.lua`
`doxyrest-2.1.2-linux-x86/bin/doxyrest: error while loading shared libraries: libexpat.so.1: cannot open shared object file: No such file or directory`

Output of locate libexpat.so:
`/lib/x86_64-linux-gnu/libexpat.so.1`
`/lib/x86_64-linux-gnu/libexpat.so.1.6.7`
`/usr/lib/x86_64-linux-gnu/libexpat.so`

Any help would be appreciated.

**Comment by vovkos** [comment]
It looks like you are using a 32-bit build of Doxyrest on a 64-bit installation of Linux. It's possible, but then 32-bit versions of libraries must also be installed. An easier way is to simply use a 64-build of Doxyrest.

**Comment by ArchieMittal** [comment]
Thank you, amd64 version worked perfectly fine. I got mislead by the name.
