### ISSUE TITLE
group order explanation

### ISSUE THREAD

**Issue by pkp124** [vovkos/doxyrest#45]
Hello,

Could someone please help me with using the group ordering feature of doxyrest. Seems like there is a problem with doxygen alias. Is it possible to update the doc - https://vovkos.github.io/doxyrest/manual/group-order.html with maybe an example attached to how using it, will impact the final document. 

Thanks

**Comment by vovkos** [comment]
Please see this issue report: https://github.com/vovkos/doxyrest/issues/40

A solution is inside; documentation must be updated. I will try to find some time and close this and a couple of other Doxyrest issues next week. PRs are always welcome, too.

**Comment by vovkos** [comment]
Documentation updated accordingly.
