### ISSUE TITLE
page_intro.rst missing from opencv documention ?

### ISSUE THREAD

**Issue by Tryum** [vovkos/doxyrest#5]
While looking at the opencv sample, I could not find the page_intro.rst, is it missing from the repo/package or am I looking at the wrong place ?

**Comment by vovkos** [comment]
``page_intro.rst`` is not part of the repo, it's generated by ``doxyrest`` from ``xml/d1/dfb/intro.xml``

To build OpenCV do sample (and other samples):

1) unpack pre-packaged xmls with ``unpack-xml.sh`` (``unpack-xml.bat`` on Windows)

alrernatively, you can build them using ``doxygen``, but that's trickier, as it usually requires patching the original ``Doxyfile``)

2) build rsts from xmls with ``build-rst.sh`` (``build-rst.bat Release`` or ``build-rst.bat Debug``  on Windows)

3) build htmls with ``build-html.sh`` (``build-html.bat`` on Windows)

You can also follow the travis-ci/appveyor-ci build logs -- it's very helpful with troubleshooting the build process.

**Comment by Tryum** [comment]
Thanks for the info (and for the tool) ;)

**Comment by vovkos** [comment]
You are very welcome :)
