### ISSUE TITLE
can't find base compound refid: cpp/types/integral_constant

### ISSUE THREAD

**Issue by dhanjit** [vovkos/doxyrest#8]
error: can't find base compound refid: cpp/types/integral_constant

I am providing tags from cppreference in doxyfile

```
TAGFILES               = "doxygen/resources/cppreference-doxygen-web.tag.xml=http://en.cppreference.com/w/"
```

**Comment by vovkos** [comment]
Steps to reproduce? Could you provide the original C++ project or at least the Doxygen XML database?

**Comment by vovkos** [comment]
No hints for the issue reproduction were given. Most likely, HIDE_UNDOC_RELATIONS was set to default (FALSE) and it caused bogus links to omitted members or template arguments. Closing now.
